### ISSUE TITLE
Helping the user bring the right things based on the weather

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-jan-2022#4]
- If it's raining, bring an umbrella
- If it's sunny, bring suncream
- If it's cold, bring a coat

**Comment by adizcode** [comment]
Interested!

**Comment by Chukwuemeka-Mba** [comment]
Interested ⛳️

**Comment by VaibhaveS** [comment]
Interested!

**Comment by Aniket762** [comment]
Hey, @Chukwuemeka-Mba @VaibhaveS @adizcode let me know how you folks want to collaborate. I personally believe the issue is small and if two of us work on this will be easier to work on and the flow will also be pretty smooth. I have no issues working together, let me know how you plan out to do the task.

As of now I am creating a branch to work on and writing the basic logic 😁

**Comment by Aniket762** [comment]
Hey @adizcode @VaibhaveS @Chukwuemeka-Mba I have worked on the issue and it works fine on `clear` and `cloudy`, please add other cases with SVGs or graphics to make it scalable. The component is properly functional. Currently, it lacks `use cases` and CSS which may result in some errors. You may see the forked repo I have given access to you all to work on it. The current changes are made on the `issue-4` branch in my repo. In case of any issue let me know. 

You may refer to this for more use cases: https://openweathermap.org/weather-conditions

**Comment by adizcode** [comment]
@Aniket762 I've pushed the changes to your fork. Please take a look and open a PR as you see fit. 

I'll add Lottie as well once I'm done on some other issues.
